t9md/atom-narrow

README.md, keymaps/narrow.cson, lib/main.coffee, lib/provider/bookmarks.coffee, lib/provider/fold.coffee, lib/provider/git-diff.coffee, lib/provider/lines.coffee, lib/provider/provider-base.coffee, lib/provider/search.coffee, lib/provider/symbols.coffee, lib/ui.coffee, lib/utils.coffee, styles/narrow.less
- Tried but was super difficult, so added `force-refresh` command to allow use manual-redraw
=> Make it stable

lib/provider/provider-base.coffee, lib/ui.coffee, lib/utils.coffee
Aiming to fix #58
On `updateRealFile`, check each line startsWith lineHeader.
Not perfect I know, but it probably protect 99.9% situation.
This is happens in multi-cursor situation.
e.g. `ctrl-alt-g`(`find-and-replace:select-all`) to change all word in narrowEditor.
e.g. `c o f` in vim-mode-plus, `change` `occurrence` in `a-function`
In this case, destroy cursor on prompt row(it can be also multiple) and recover query on prompt.
On `updateRealFile`, ensure item's total line number not changed when last generated items to narrow.
=> More protection for narrowEditor in direct-edit

keymaps/narrow.cson, lib/main.coffee, lib/provider/provider-base.coffee, lib/settings.coffee, lib/ui.coffee
#67
Remove config option for vmp integration and get it right by default.
Avoid heavy integration with vmp, instead use `atom.commands.dispatch` since it's work!
- `narrow:focus-prompt`
- Focus to prompt and start `insert-mode` unless cursor is already at prompt.
- If cursor is already at prompt, focus back to original pane.
- `narrow:focus`
- Focus to narrow-editor if it's not focused.
- If focused, focus back to original pane.
- No longer auto-start `insert-mode` for cursor move within narrow-editor.
- Auto-start-insert-mode is done in following case.
- When starting narrow, since it start with cursor on prompt.
- User invoked `narrow:focus-prompt` command.
=> Simplify vim integration

lib/main.coffee, lib/provider/provider-base.coffee, lib/provider/symbols.coffee, lib/ui.coffee, lib/utils.coffee
Implement idea described in #77
Now all boundToEditor providers are re-bound to **different editor**.  
So usage is greatly enhanced. Keep `narrow:symbols` or `narrow:fold` opend. and changing tab to activate different editor.
Each time you switch tab, symbols or fold items are refreshed and auto sync to current cursor position.
In this usage narrow is getting closer to minimap. But it's narrowable, readable text, clickable and editable(direct-edit-and-save-to-real-file).
- Re-bind is happened `onDidStopChangingActivePaneItem`.
- So code are modified to
- Not store static reference for `@provider.editor` in different component.
- So `@providerEditor = @provider.editor` in `Ui` code no longer acceptable.
- Since `provider.editor` can be changed(re-bound) multiple time.
- Event …
=> Make provider re-bindable to different editor

README.md, lib/settings.coffee, lib/ui.coffee
Fix #86
- Overwrite, TextBuffer's `isModified` function to update modified icon on tab(provided by core `tabs` package).
- Now cofirm user before `update-real-file` really update real file.
- New option `confirmOnUpdateRealFile`(default `true`).
- If this was set to `false`, no longer ask before `update-real-file`, danger!
- As I wrote in #86, I did experiment to override `core:save` and other simlar approach
- But I decided that 'its ok to let user just override `cmd-s` to `narrow-ui:update-real-file`'.
- Overriding `core:save` is too aggressive, so intentionally avoided(or postponed).
=> more intuitive flow for update-real-file

keymaps/narrow.cson, lib/ui.coffee
Aiming to fix #92
:tada: Greatly improve usability!
keymap is available on `narrow-editor` with scoped `vim-mode-plus.normal-mode` or `read-only` mode.
- `narrow-ui:exclude-file`: `backspace`, Exclude currently selected file from result.(no effect in boundToEditor provider)
- `narrow-ui:clear-excluded-files`: `ctrl-backspace`, Clear exclude-file list. and refresh
- `narrow-ui:move-to-next-file-item`: `n`, Move to first-item of next-file.
- `narrow-ui:move-to-previous-file-item`: `p` Move to last-item of previous-file.
=> exclude particular file manually

lib/main.coffee, lib/provider/atom-scan.coffee, lib/provider/search-base.coffee, lib/provider/search.coffee
- `narrow:search-file`
- `narrow:search-file-by-current-word`
- `narrow:atom-scan-file`
- `narrow:atom-scan-file-by-current-word`
- Now atom-scan display project-header and file-header relativised.
=> search-file and atom-scan-file

keymaps/narrow.cson, lib/highlighter.coffee, lib/main.coffee, lib/provider/atom-scan.coffee, lib/provider/provider-base.coffee, lib/provider/scan.coffee, lib/provider/search-base.coffee, lib/provider/search.coffee, lib/settings.coffee, lib/ui.coffee, lib/utils.coffee
Fixes #111
`narrow:scan` have some special, exceptional characteristics for how it react narrow queries.
- Use first include narrow query as scan term.
- Rest of include and exclude queries are treated as normal filter query.
- To make this exceptional query handling obvious by eye, use different syntax grammar highlight for first query(= scan term).
- it start with empty items, since no query means no scan-term provided.
=> narrow:scan as better narrow:line

lib/grammar.coffee, lib/provider-information.coffee, lib/provider/provider-base.coffee, lib/provider/scan.coffee, lib/provider/search-base.coffee, lib/ui.coffee, styles/narrow.less
first step to fixes #115
- Show button to toggle `ignoreCase`, `wholeWord`, item count, loading indicator.
- Show tooltips on mouseover.
- For providers `scan`, `search`, `atom-scan`
- Achieved by block-decoration(since I want keep `narrow-editor` really normal text-editor).
- Recover block-decoration(destroy and re-decorate) when prompt on accidental prompt row removal.
- For scan, search term can be changed multiple-time
- Unless manually changed by button or shortcut, it respect `caseSensitivityForSearchTerm`
=> show search option info on ui and toggle options by click

CHANGELOG.md, lib/provider/provider-base.coffee, lib/provider/scan.coffee, lib/provider/search-base.coffee
Fix #127
- Original idea was to improve usefulness of `narrow:scan`.
- But I found this is also benefits for `narrow:search`, `narrow:atom-scan`.
- Background is pattern `\b@word\b` is completely useless(it never match).
- In this case what user want to search is `@word\b`.
- But atom-narrow's `\b` button is stupidly surround term with `\b` so, `@word\b` is never searchable.
- In atom's `find-and-replace`, user can search `@word\b` by manually enter regex. but whole-word option's behavior is same as current atom-narrow(useless).
- What I want to do here, is **relax `\b` boundary as long as start or end can match with `\b` boundary**.
- So when `whole-word`(`\b`) option  is enabled
- `editor` => `\beditor\b` ( start and end is word-char).
- `@editor` => `@editor\b` ( relaxed start boundary …
=> auto-relax word-boundary(`\b`) in whole-word search

lib/highlighter.coffee, lib/provider/provider-base.coffee, lib/provider/scan.coffee, lib/provider/search-base.coffee, lib/ui.coffee, styles/narrow.less
Fixes #120
Main purpose is "**to less noisy, avoid verbosity, no disturb when editing**"".
- Avoid flash when directly confirmed ( avoid verbosity ).
- Flash when next-item / previous-item ( to let me to know where I landed )
- Remove `ProviderBase.prototype.useHighlighter` flag
- if item have range field, flash else flash row for point?
- Current `onDidStopChangingActivePaneItem` is too late when intentional confirmation.
=> flash current match / show current-marker only on preview

lib/highlighter.coffee, lib/main.coffee, lib/provider/provider-base.coffee, lib/provider/search-base.coffee, lib/settings.coffee, lib/ui.coffee, lib/utils.coffee
#135 
- Allow `narrow-editor` open in **pending** state
- activate providerPane after open if `activate` was set to `alse` on UI constructor ( default = true )
- mouse double click start `narrow:scan-by-current-word` if configured.
=> double click start search / allow narrow-editor open in pending state

lib/provider/symbols.coffee
The `language-markdown` package, which is a drop-in replacement for `language-gfm`, uses the grammar scope `text.md` instead of `source.gfm`.
This pull request adds `text.md` to the grammar scopes that get special indentation handling for markdown headers in the symbols provider.
=> Support text.md grammar scope for special indentation handling of symbols provider

lib/provider/atom-scan.coffee, lib/provider/bookmarks.coffee, lib/provider/git-diff-all.coffee, lib/provider/linter.coffee, lib/provider/project-symbols.coffee, lib/provider/provider-base.coffee, lib/provider/search-base.coffee, lib/provider/search.coffee, lib/ui.coffee, lib/utils.coffee
Fixes #105
- Now `atom-scan` and `search` can re-scan per filePath.
- projectName and filePath header injection is done by Ui on every refresh() for simplicity.
- Even in per filePath refresh, ui, re-render whole items area for simplicity.
- I won't partial render for items area until I find it really necessary.
* Completely new file is always added to end of items.
1. when `filePath-A` contains `abc`, and `scan`.
items for `filePath-A` rendered on `narrow-editor`
2. Delete all `abc` from `filePath-A` then save.
items for `filePath-A` removed from `narrow-editor`
3. Add `abc` to `filePath-A` then save.
items for `filePath-A` appended to existing items and rendered at bottom of `narrow-editor`.
- Even if items for `filePath-A` appeared at **top of** `narrow-editor` at **1**.
- Items are …
=> per file refresh support for search and atom-scan

CHANGELOG.md, README.md, lib/control-bar.coffee, lib/provider/provider-base.coffee, lib/provider/select-files.coffee, lib/settings.coffee, lib/ui.coffee
Fix #162
`select-files` provider is available for not `boundToSingleFile` provider.
Which is available for `o` marked providers.
- o `atom-scan`
- o `bookmarks`
- o `git-diff-all`
- o `linter`
- o `project-symbols`
- o `search`
- New `rememberQuery` config for `select-files` provider
- When set to `true`, remember query **per provider basis** and apply it at startup.
- When `narrow:reopen` initial `select-files` query applying is skipped to respect restored `excludedFiles`.
- Improve: folder-icon on `control-bar` highlighted when some files are excluded.
- This is indicating files are **actually** excluded( filtered ).
- If remembered `select-files` was applied but no file exclusion happens, then no-highlight.
- e.g. Applying remembered `.md!` query to non-markdown-file-items have no …
=> config to preserve query-for-select-files across provider/same-provider

lib/get-filter-spec-for-query.coffee, lib/provider/project-symbols.coffee, lib/provider/provider-base.coffee, lib/provider/symbols.coffee
Fix #169
Related #50
Add query expression which specify word-boundary(`\b`) search.
Here is how query translated
```
if /^>./.test(pattern)
```
If `\b` is meaningless(e.g. `>=`), it don't add `\b`, but remove `>` or `<` for consistency.
NOTE: I also evaluated not-trim starting `>` so that user don't need to search by `>>=` for search `>=` literal.  
But it was not obvious when `>` is removed or not removed, which make user learning difficult, so avoided this approach.
Purpose: To make quick previewing by `symbols-by-current-word` or `project-symbols-by-current-word` further useful.
1. Place cursor on `@refresh` function and invoke
2. `narrow:symbols-by-current-word`: Previewing unwanted function(multiple symbols which contains `refresh`)
3. `narrow:project-symbols-by-current-word`: …
=> add query expression for word-boundary and use it in symbols and project-symbols

lib/get-filter-spec-for-query.coffee
#174
Experimentally add `|` as OR expression for narrow-query.
- `wordA|wordB` matches items include `wordA` **or** `wordB`.
- Can chain multiple `OR`, `a|b|c` matches items for `a` or `b` or `c`.
- query `a|b|c d` means, matches items (`a` or `b` or `c`) and also maches `d`.
- General rule: `|` is treated as `OR`, white-space is always treated as `AND`.
- This `OR` handling is NOT happen when query word starts or ends with `|` char.
- e.g. `|a`, `a|`, `|a|b` , `a|b|`, `|a|b|`, all searched as-is(literally), `|` is **not** evaluated as `OR`.
=> add narrow-query OR(|) expression

CHANGELOG.md, lib/provider/provider-base.coffee, lib/settings.coffee, lib/ui.coffee
Fix #177
- new config param `focusOnStartCondition`
- This config control whether initially focus to `narrow-editor` or not.
- Possible values are
- `never`: never focus to `narrow-editor` on start.
- `always`: always focus to `narrow-editor` on start( default ).
- `no-input`: focus when initial query was empty( limitation: for `search`, `atom-scan` this value is not supported )
- This is very experimental feature, might be removed in future( after evaluated I found I myself don't need this ).
=> [experiment] activateOnStart config param

lib/provider/scan.coffee
By NOT using `editor.scan`, `narrow:scan` get much faster.
1. open `text-editor.coffee` of atom-core's source
2. start `narrow:scan`
3. type initial char
Result for different initial char
```
scan:new:r: 8.806ms
scan:old:r: 29.064ms
scan:new:o: 8.588ms
scan:old:o: 18.918ms
scan:new:t: 10.766ms
scan:old:t: 30.820ms
scan:new:l: 4.183ms
scan:old:l: 28.233ms
scan:new:o: 4.252ms
scan:old:o: 14.475ms
```
=> faster scan

keymaps/narrow.cson, lib/main.coffee, lib/query-history.coffee, lib/ui.coffee, lib/utils.coffee
Fix #180
- Duplicate text is not saved.
- Empty text is not saved.
- Timing of save is
- `Ui::open`: to save query of `by-current-word`
- `Ui::destroy`: to save interactive search term
- `Ui::queryCurrentWord`: to save `query-current-word`.
- Through explicit command, example keymap is here.
- By scoping `narrow-editor.prompt`, this command keymap is effective only when cursor is at prompt row.
```coffeescript
'atom-text-editor.narrow.narrow-editor.prompt.vim-mode-plus.insert-mode[data-grammar="source narrow"]':
'ctrl-p': 'narrow-ui:previous-query-history'
'ctrl-n': 'narrow-ui:next-query-history'
```
=> Support query history

lib/provider/atom-scan.coffee, lib/provider/fold.coffee, lib/provider/git-diff-all.coffee, lib/provider/project-symbols.coffee, lib/provider/provider-base.coffee, lib/provider/scan.coffee, lib/provider/search.coffee, lib/provider/symbols.coffee, lib/ui.coffee
#181
- Refresh is called at following timing
- `boundToSingleFile` providers: `onDidStopChanging` (e.g. scan, fold)
- non `boundToSingleFile` providers: `onDidSave` (e.g. search, atom-scan)
- Refresh is called based on following props on provider
- `refreshOnDidStopChanging`
- `refreshOnDidSave`
- Each provider must explicitly set these props if they want to refresh on these event.
- `search`, `atom-scan` use `ProviderBase::scanItemsForEditor` to re-scan file filePath.
- This method is same method which `scan` provider mainly use.
=> item can refresh on did stop changing for search

CHANGELOG.md, lib/provider/git-diff-all.js
refresh items list on text change, instead of on-save.
Why this is useful?
Typical scenario where this feat shines is
- When I adde dirty `console.log` in multiple place.
- I want to delete these one.
- I can use `git-dif-all` which shows `console.log` lines as long as important modification.
- I can filter by `console` then `tab`, delete-line, `tab`, delete-line till remove all the garbage debug print line.
=> make git-diff-all provider change aware

CHANGELOG.md, lib/provider/git-diff-all.js, lib/provider/provider-base.js
This fix should be backported manually to atom-narrow for Atom-stable(v.1.18).
This is degradation introduced when I fixed #232 
In #232 I began to use `TextBuffer.load` which just load file from disk, so modified state of existing buffer is just ignored which was super **bad** when user trying to `update-real-file`.
Here is example situation
1. search `abc`, ui shows many items that matches `abc`.
2. modify some `abc` including line on some editor, then item list automatically be updated, since items are unsaved-change-aware(read from existing buffer for modified file).
3. modify items in `ui` directly and `update-real-file`. To mutate file content, I need buffer instance. Using `TextBuffer.load` means, load fileContent from disk, but here we should refer existing buffer content to …
=> [CRITICAL] fix modified buffer state is ignored on directEdit

lib/ui.js
Fix #239 
No sure when this issue started, maybe this was original behavior of Atom.
narrow didn't use onDidChangeScrollTop event before, since it's is now used for decoration narrow-editor highlight but it was done by grammar.
from Atom v1.19 , Atom support text decoration which allow foreground color change, and narrow starting to use this approach to highlight narrow-editor.
Anyway what was happened is
1. onDidChangeScrollTop was fired
2. clear highlight which eventually fire onDidChangeScrollTop with same value in some situation
3. loop between 1-2 which freeze Atom.
I didn't investigated why 2 is happened(IMO, event should not be fired with same scrollTop).
=> onDidChangeScrollTop can be recursively fired and freeze Atom

README.md, lib/highlighter.js, lib/items.js, lib/provider/provider-base.js, lib/settings.js, lib/ui.js, lib/update-real-file.js, lib/utils.js, styles/narrow.less
Alternate approach for #242
Truncate long line by narrow itself instead of doing truncation at searcher(`ag`, `rg`) level.
- This is super important. It's **after** item gathering/filtering phase.
- Even if there were truncated item on narrow-editor, as long as it's not used for updating, should that operation allowed.
- So validate very last timing that items to update not including truncated-item.
=> Truncate long line

lib/utils.js
The method got changed from `dir.getPath()` to `dir.getPaths()` at e9ce92d9512d84e74d11a50de07f07f72c20b277, which broke 'search-current-project-by-current word' for me.
Locally, changing it back to `dir.getPath()` appear to fix it.
=> Fix utils.getProjectPaths causing breakage in 'search-current-project-by-current word'

lib/control-bar.js, lib/main.js, lib/provider/git-diff-all.js, lib/provider/provider-base.js, lib/settings.js, package.json, styles/narrow.less
Added integration with [inline-git-diff](https://github.com/t9md/atom-inline-git-diff) pkg.
Depends https://github.com/t9md/atom-inline-git-diff/pull/3
- While reviewing changes before commit by `git-diff-all`.
- Show `inline-git-diff` which is auto-enabled on GitDiffProvider opened editor and diff disabled on ui destroy.
- Catch accidental removal remaining `console.log` etc..
- Revert is easy by `inline-git-diff:revert` command(I map it to `g r` for `editor.has-inline-git-diff` scope)
```CoffeeScript
'atom-workspace:not(.has-narrow) atom-text-editor.vim-mode-plus.normal-mode.has-inline-git-diff':
'tab': 'git-diff:move-to-next-diff'
'shift-tab': 'git-diff:move-to-previous-diff'
'atom-text-editor.vim-mode-plus.normal-mode.has-inline-git-diff':
'g r': 'inline-git-diff:revert'
'g c': …
```
=> Provider git diff all use inline git diff service

CHANGELOG.md, lib/item-reducer.js, lib/query-history.js, lib/ui.js
Summary
- Do not auto-visit item when cursor is at prompt.
- For `atom-scan`, `search`, `scan` provider, save history on confirm in addition to existing save timing.
History feature itself was provided from older version with default keymap.
- `ctrl-cmd-[`(`narrow:previous-query-history`)
- `ctrl-cmd-]`(`narrow:next-query-history`)
User can recall query-history from both inside and outside(when narrow-editor is not focused) narrrow-editor.
But for user who want to recall query-history from narrow-editor's prompt as like normal search-tool, define following keymap in `keymap.cson`.
:warning: NOTE: This is vim-mode-plus user specific example!! :warning:
```coffeescript
'atom-text-editor.narrow.narrow-editor.vim-mode-plus.insert-mode.prompt':
'up': 'narrow:previous-query-history'
'down': …
```
=> Improve history handling

CHANGELOG.md, lib/narrow-editor.js, lib/ui.js
automatically append single space `' '` when user execute `move-to-prompt` command so that user can continue new query immediately.
This is auto-append have pros and cons.
I won't say improvement for everyone.
Will see reaction in the wild.
=> auto-append-space after query when user's explicit move-to-prompt

lib/provider/provider.js, lib/settings.js, lib/ui.js, lib/utils.js
vmp have feature to maximize currently active pane by `cmd-enter` etc..
Basically this maximized state is restored(unmaximized) when pane split happened.
Since narrow open narrow-editor with splitting-pane, opening narrow always de-maximize this maximized-state.
This PR re-maximize pane when narrow-editor(=ui) was closed if it's originally maximized.
Default enabled, but user can disable this by configuration `restoreVmpPaneMaximizedStateOnUiClosed`.
=> restore vmp's pane-maximized-state on ui destroyed

CHANGELOG.md, lib/main.js
Fix #281 
- Fix: When `narrow:scan` start without any input, don't preview first row item #281
- This is regression introduced in v0.60.0.
- Plus: No longer start auto-preview when prompt query was clicked.
=> dont start auto-preview when cursor is at prompt

lib/narrow-editor.js, lib/provider/atom-scan.js
- `atom-scan` provider originally supported `directEdit` feature
- But I [removed this feature](d1f5416) when I noticed something dangerous could be happen in `atom-scan` provder.
- Why? `atom-scan` use `workspace.scan` which returns **truncated lineText**(truncation happens both in leading or trailing place).
- `update-real-file`(direct-edit) is done by **replacing exiting-whole-line-text with new-whole-line-text**, cannot/won't handle replacing partial text.
- Now: I'm trying to re-introduce this feature(come back!) with keep in mind `workspace.scan`'s result is **truncated**.
By ignoring result.lineText and use real buffer’s non-truncated
- `workspace.scan`'s result have `linetText` and `lineTextOffset`
- `lineText` might be **truncated**
- Leading truncation: When `lineTextOffset > 0 …
=> atom-scan now direct-editable again

lib/provider/atom-scan.js, lib/provider/fold.js, lib/provider/git-diff-all.js, lib/provider/project-symbols.js, lib/provider/provider.js, lib/provider/scan.js, lib/provider/search.js, lib/provider/select-files.js, lib/provider/symbols.js, lib/ui.js
This is breaking change.
How? `provider.finishUpdateItems` method was removed.
This affect how `getItems()` should be implemented.
Related: #207, #272 
If all items are collectable synchronously, call `finishUpdateItems` with items.
```javascript
getItems() {
this.provider.finishUpdateItems(items)
}
```
If items are collected async with multiple separate chunks, call `updateItems` multiple times, then call `finishUpdateItems` to notify **done**.
```javascript
async getItems() {
await new Promise(resolve) {
this.provider.updateItems(items)
this.provider.updateItems(items)
this.provider.updateItems(items)
resolve()
}
this.provider.finishUpdateItems()
}
```
The `finishUpdateItems` method is removed, `return` items instead.
If all items are collectable synchronously, return items. …
=> simplify getItems, no longer require to call finishUpdateItems

lib/update-real-file.js
pass `atom.confirm` a callback allowing async handling
of user confirmation
=> fix: Update Real File w/ confirmation prompt
