t9md/atom-narrow

keymaps/narrow.cson
lib/main.coffee
lib/provider/lines.coffee
lib/provider/provider-base.coffee
lib/provider/search.coffee
lib/ui.coffee

set objective command

---

lib/provider/atom-scan.coffee
lib/provider/bookmarks.coffee
lib/provider/fold.coffee
lib/provider/git-diff.coffee
lib/provider/lines.coffee
lib/provider/provider-base.coffee
lib/provider/search-base.coffee
lib/provider/search.coffee

consolidate search and atom-scan

---

lib/ui.coffee

make bindToEditor multiple times to different editor

---

lib/provider/provider-base.coffee
lib/provider/search.coffee
lib/settings.coffee
lib/ui.coffee

sorry for early adapter user...
Config param for provider was changed  for maintainability.
But I won't provider auto-migration mechanism(my excuse is it's still alpha stage).

Cleanup provider config

---

lib/main.coffee
lib/ui.coffee
lib/utils.coffee

auto-sync for search provider(for non boundToEditor providers)

---

keymaps/narrow.cson
lib/ui.coffee
styles/narrow.less

Readonly item area for non-vim-mode-plus user

---

lib/provider/provider-base.coffee
lib/ui.coffee
lib/utils.coffee

differentiate preview and confirm for performant preview

---

CHANGELOG.md
lib/grammar.coffee
lib/provider/atom-scan.coffee
lib/provider/bookmarks.coffee
lib/provider/fold.coffee
lib/provider/git-diff.coffee
lib/provider/lines.coffee
lib/provider/linter.coffee
lib/provider/provider-base.coffee
lib/provider/search-base.coffee
lib/provider/search.coffee
lib/provider/symbols.coffee
lib/settings.coffee
lib/ui.coffee

Show multiple matches on same row as different items

---

CHANGELOG.md
lib/provider/atom-scan.coffee
lib/provider/provider-base.coffee
lib/provider/search-base.coffee
lib/ui.coffee
lib/utils.coffee
styles/narrow.less

highlight matches for search/atom-scan provider

---

lib/item-indicator.coffee
lib/main.coffee
lib/provider-panel.coffee
lib/provider/scan.coffee
lib/ui.coffee
styles/narrow.less

refresh, lock, auto-preview button on provider-panel

---

README.md
lib/highlighter.coffee
lib/main.coffee
lib/provider/fold.coffee
lib/provider/git-diff.coffee
lib/provider/lines.coffee
lib/provider/provider-base.coffee
lib/provider/scan.coffee
lib/provider/symbols.coffee
lib/settings.coffee
lib/ui.coffee
package.json

#141 
- Revealing initially is super useful for many provider.
- Maybe `helm-swoop` feature covered by this enhancement.
- I'll consider opinionated / reasonable default value for that.

autoRevealOnStart

---

CHANGELOG.md
lib/highlighter.coffee
lib/items.coffee
lib/provider-panel.coffee
lib/ui.coffee
package.json

To reduce size of `ui.coffee` for maintainability

Extract item concern logic from UI

---

lib/input-history-manager.coffee
lib/input.coffee

support input history for  search, atom-scan

---

CHANGELOG.md
README.md
lib/main.coffee
lib/provider/provider-base.coffee
lib/provider/scan.coffee
lib/provider/search-base.coffee
lib/provider/search.coffee

reopen last-closed narrow

---

CHANGELOG.md
README.md
lib/main.coffee
lib/provider/provider-base.coffee
lib/provider/scan.coffee
lib/provider/search-base.coffee
lib/settings.coffee
lib/ui.coffee
spec/narrow-spec.coffee
spec/spec-helper.coffee

rememberIgnoreCase search/atom-scan option

---

.travis.yml
lib/main.coffee
lib/provider/search.coffee
spec/fixtures/project1/p1-f1
spec/fixtures/project1/p1-f2
spec/fixtures/project1/p1-f3.php
spec/fixtures/project2/p2-f3.php
spec/narrow-spec.coffee

fix fix-regex-semantics-diff-bug for search

---

README.md
lib/provider/provider-base.coffee

Fix #187, #186 in atom 1.17.0 or later

[partial fix] Dont activate provider-pane on preview from atom v1.17.0

---

lib/ui.coffee
spec/helper.coffee

Dlay refresh on query-change event for non-disturbing refresh

---

keymaps/narrow.cson
lib/highlighter.coffee
lib/input.coffee
lib/items.coffee
lib/provider/provider-base.coffee
lib/provider/scan.coffee
lib/provider/search-base.coffee
lib/provider/search.coffee
lib/ui.coffee
spec/narrow-spec.coffee
styles/narrow.less

support RegExp search for narrow:search

---

lib/control-bar.coffee
lib/input-history-manager.coffee
lib/input.coffee
lib/items.coffee
lib/provider/provider-base.coffee
lib/provider/scan.coffee
lib/provider/search-base.coffee
lib/settings.coffee
lib/ui.coffee
lib/utils.coffee
spec/narrow-spec.coffee

More accurate reveal

---

lib/item-reducer.coffee
lib/main.coffee
lib/provider/atom-scan.coffee
lib/provider/git-diff-all.coffee
lib/provider/provider-base.coffee
lib/provider/search.coffee
lib/provider/symbols.coffee
lib/searcher.coffee
lib/settings.coffee
lib/ui.coffee
package.json
spec/narrow-spec.coffee

Fix #207
Start from very rough state, since I don't have clear understanding of the requirement for other people well.

[experiment] provide service to support external provider

---

keymaps/narrow.cson
lib/provider/provider-base.js
lib/ui.js

:gift: narrow-ui:open-at-here

---

lib/searcher.js

Feel free to change error message

Search engine check

---

README.md
keymaps/narrow.cson

Remove lots of keymaps which conflicts vmp

---

lib/highlighter.js
lib/item-indicator.js
lib/items.js
lib/main.js
lib/provider/atom-scan.js
lib/provider/fold.js
lib/provider/git-diff-all.js
lib/provider/project-symbols.js
lib/provider/provider-base.js
lib/provider/scan.js
lib/provider/search.js
lib/provider/select-files.js
lib/provider/symbols.js
lib/search-options.js
lib/searcher.js
lib/settings.js
lib/ui.js
lib/utils.js

just did harmless(I believe so) cleanup including prettified with latetest prettier

cleanup as refresher

---

lib/highlighter.js
lib/item-editor.js
lib/items.js
lib/main.js
lib/provider/provider.js
lib/provider/select-files.js
lib/ui.js
lib/update-real-file.js
spec/helper.js
styles/narrow.less

`ui.js` is too big for me, try to extract ui.editor concerns to itemEditor.

Extracting ui.editor concerns as itemEditor

---

CHANGELOG.md
README.md
lib/control-bar.js
lib/items.js
lib/main.js
lib/narrow-editor.js
lib/provider/provider.js
lib/settings.js
lib/ui.js
lib/utils.js
spec/helper.js
spec/narrow-spec.js
styles/narrow.less

dock-able narrow-editor

---

lib/highlighter.js
lib/main.js
lib/provider/provider.js
lib/ui.js
lib/utils.js

Still hit #247 occasionally.
This PR is attempt to hit #247 issue **hopefully**.
And added assertion to clearly catch unwanted situation.

Refine preview while starting

---

lib/control-bar.js
lib/main.js
lib/narrow-editor.js
lib/provider/fold.js
lib/provider/git-diff-all.js
lib/provider/provider.js
lib/settings.js
lib/ui.js
lib/update-real-file.js
lib/utils.js
package.json
spec/helper.js
spec/narrow-spec.js
styles/narrow.less

Ref
https://github.com/t9md/atom-outlet
https://github.com/t9md/atom-outlet-manager

Use atom-outlet

---

lib/provider/search.js
lib/searcher.js
lib/settings.js

Allow searcher command options

---

lib/ui.js

fix deprecation warning for undo = skip option for setTextInBufferRange
